filegroup(
    name = "sonarsweep",
    srcs = glob(["dev/chadxz/adventofcode/sonarsweep/**/*"]),
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "dive",
    srcs = glob(["dev/chadxz/adventofcode/dive/**/*"]),
    visibility = ["//:__subpackages__"],
)
